sentence([('﻿http://t.co/frbYEpxvTa', '﻿http://t.co/frbYEpxvTa', 'link')]).

sentence([('bsm', 'bsm', 'NN'), ('Allh', 'Allh', 'NNP'), ('AlrHmn', 'AlrHmn', 'NNP'), ('AlrHym', 'AlrHym', 'NNP'), ('{', '{', 'PUNC'), ('ql', 'ql', 'VB'), ('hw', 'hw', 'PRP'), ('Allh', 'Allh', 'NNP'), ('>Hd', '>Hd', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('Allh', 'Allh', 'NNP'), ('AlSmd', 'AlSmd', 'NNP'), ('COMMA', 'COMMA', 'COMMA'), ('lm', 'lm', 'RP'), ('y', 'y', 'TNS'), ('ld', 'ld', 'VB'), ('wlm', 'wlm', 'RP'), ('y', 'y', 'TNS'), ('wld', 'wld', 'VB'), ('COMMA', 'COMMA', 'COMMA'), ('wlm', 'wlm', 'RP'), ('y', 'y', 'TNS'), ('kn', 'kn', 'VB'), ('lh', 'lh', 'PRP'), ('kf', 'kf', 'VB'), ('wA', 'wA', 'PERS'), ('>Hd', '>Hd', 'NN'), ('}', '}', 'NN'), ('(', '(', 'PUNC'), ('vlAv', 'vlAv', 'NN'), ('mrAt', 'mrAt', 'NN'), (')', ')', 'NN'), ('A*kAr', 'A*kAr', 'NN'), ('grd', 'grd', 'NN'), ('b*kr', 'b*kr', 'NN'), ('Allh', 'Allh', 'NNP')]).

sentence([('★', '★', 'emoj'), ('★', '★', 'emoj'), ('☆', '☆', 'emoj'), ('☆', '☆', 'emoj'), ('★', '★', 'emoj'), ('@', '@', 'MEN'), ('BankAljazira', 'BankAljazira', 'username'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('>shl', '>shl', 'JJ'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('bTAqp', 'bTAqp', 'NN'), ('nAdyk', 'nAdyk', 'NNP'), ('mn', 'mn', 'IN'), ('bnk', 'bnk', 'NN'), ('Aljzyrp', 'Aljzyrp', 'NNP'), ('tqdm', 'tqdm', 'NN'), ('bTlb', 'bTlb', 'NN'), ('k', 'k', 'SPRP'), ('Al|n', 'Al|n', 'NN'), ('http://t.co/M7je55XkcV', 'http://t.co/M7je55XkcV', 'link'), ('http://t.co/cUrksqYlAE.Ktb', 'http://t.co/cUrksqYlAE.Ktb', 'link'), ('1', '1', 'CD')]).

sentence([('@', '@', 'REP'), ('yahoo53389086', 'yahoo53389086', 'username'), ('Allh', 'Allh', 'NNP'), ('Allh', 'Allh', 'NNP'), ('DQUOTE', 'DQUOTE', 'DQUOTE'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('AHrjtyny', 'AHrjtyny', 'JJ'), ('mn', 'mn', 'IN'), ('jd', 'jd', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('mAqwl', 'mAqwl', 'NN'), ('gyr', 'gyr', 'NN'), ('$kr|', '$kr|', 'NN'), ('mn', 'mn', 'IN'), ('AﻵEmAq', 'AﻵEmAq', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('!', '!', 'PUNC')]).

sentence([('t', 't', 'TNS'), ('SbH', 'SbH', 'VB'), ('wn', 'wn', 'PERS'), ('ElY', 'ElY', 'IN'), ('xyr', 'xyr', 'NN')]).

sentence([('lAyq', 'lAyq', 'VB'), ('Elyq', 'Elyq', 'NN'), ('AlAbyD', 'AlAbyD', 'JJ'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('lAswd', 'lAswd', 'VB'), ('http://t.co/0RzCd4tsxo', 'http://t.co/0RzCd4tsxo', 'link')]).

sentence([('Al', 'Al', 'ART'), ('mgzY', 'mgzY', 'NN'), ('mn', 'mn', 'IN'), ('hAlklAm', 'hAlklAm', 'NN'), ('hw', 'hw', 'PRP'), ('sbH', 'sbH', 'NN'), ('An', 'An', 'AGR'), ('mn', 'mn', 'IN'), ('y', 'y', 'TNS'), ('zrE', 'zrE', 'VB'), ('Hb', 'Hb', 'NN'), ('$xS', '$xS', 'NN'), ('mA', 'mA', 'NN'), ('$ft', '$ft', 'NN'), ('h', 'h', 'SPRP'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('Erf', 'Erf', 'VB'), ('t', 't', 'PERS'), ('h', 'h', 'SPRP'), ('bqlb', 'bqlb', 'NN'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('y', 'y', 'TNS'), ('nzE', 'nzE', 'VB'), ('Hb', 'Hb', 'NN'), ('$xS', '$xS', 'NN'), ('A', 'A', 'TNS'), ('Erf', 'Erf', 'VB'), ('h', 'h', 'SPRP'), ('mn', 'mn', 'IN'), ('f', 'f', 'CC'), ('trp', 'trp', 'NN'), ('Twylp', 'Twylp', 'JJ')]).

sentence([('AsEdAl', 'AsEdAl', 'NN'), ('h', 'h', 'SPRP'), ('msA}', 'msA}', 'NN'), ('km', 'km', 'SPRP'), ('bkl', 'bkl', 'NN'), ('xyr', 'xyr', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('COMMA', 'COMMA', 'COMMA'), ('@', '@', 'REP'), ('abo_hesam', 'abo_hesam', 'username'), ('l', 'l', 'IN'), ('AHwl', 'AHwl', 'NN'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('qwp', 'qwp', 'NN'), ('AlA', 'AlA', 'IN'), ('bAllh', 'bAllh', 'NNP'), ('Al', 'Al', 'ART'), ('tsAmH', 'tsAmH', 'NN'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('Efw', 'Efw', 'NN'), ('hdAk', 'hdAk', 'RB'), ('Allh', 'Allh', 'NNP'), ('mn', 'mn', 'IN'), ('EfAG', 'EfAG', 'NN'), ('wASlH', 'wASlH', 'JJ'), ('A', 'A', 'TNS'), ('jr', 'jr', 'VB'), ('h', 'h', 'SPRP'), ('ElY', 'ElY', 'IN'), ('Allh', 'Allh', 'NNP')]).

sentence([('@', '@', 'REP'), ('Sawyerh__', 'Sawyerh__', 'username'), ('t', 't', 'TNS'), ('wqEt', 'wqEt', 'VB'), ('vqAft', 'vqAft', 'NN'), ('k', 'k', 'SPRP'), ('EAlyp', 'EAlyp', 'JJ'), ('bmA', 'bmA', 'WP'), ('y', 'y', 'TNS'), ('xS', 'xS', 'VB'), ('Al', 'Al', 'ART'), ('mSTlH', 'mSTlH', 'NN'), ('At', 'At', 'AGR'), ('Al', 'Al', 'ART'), ('$bAby', '$bAby', 'NN'), ('h', 'h', 'SPRP'), ('AlmtdAwlp', 'AlmtdAwlp', 'JJ'), ('byn', 'byn', 'NN'), ('sflp', 'sflp', 'NN'), ('Al', 'Al', 'ART'), ('qwm', 'qwm', 'NN'), ('.', '.', 'PUNC')]).

sentence([('@', '@', 'REP'), ('alaa_saeed88', 'alaa_saeed88', 'username'), ('Ax', 'Ax', 'NN'), ('ElAG', 'ElAG', 'NNP'), ('yA', 'yA', 'RP'), ('ly', 'ly', 'VB'), ('t', 't', 'PERS'), ('t', 't', 'TNS'), ('nb', 'nb', 'VB'), ('h', 'h', 'SPRP'), ('Al', 'Al', 'ART'), ('jmAhyr', 'jmAhyr', 'NN'), ('bEdm', 'bEdm', 'NN'), ('rmy', 'rmy', 'NN'), ('Al', 'Al', 'ART'), ('qwAryr', 'qwAryr', 'NN'), ('Al', 'Al', 'ART'), ('fArg', 'fArg', 'NN'), ('h', 'h', 'SPRP'), ('fy', 'fy', 'IN'), ('ArDy', 'ArDy', 'NN'), ('h', 'h', 'SPRP'), ('Al', 'Al', 'ART'), ('mlEb', 'mlEb', 'NN'), ('lAnh', 'lAnh', 'IN'), ('mtbqy', 'mtbqy', 'JJ'), ('Eqwb', 'Eqwb', 'NN'), ('h', 'h', 'SPRP'), ('w', 'w', 'CC'), ('AHd', 'AHd', 'NN'), ('h', 'h', 'SPRP'), ('w', 'w', 'CC'), ('bEd', 'bEd', 'NN'), ('hA', 'hA', 'SPRP'), ('n', 'n', 'TNS'), ('lEb', 'lEb', 'VB'), ('bdw', 'bdw', 'VB'), ('n', 'n', 'PERS'), ('jmAhyr', 'jmAhyr', 'NN')]).

sentence([('DQUOTE', 'DQUOTE', 'DQUOTE'), ('@', '@', 'RET'), ('Msa3dAlrshedi:', 'Msa3dAlrshedi:', 'username'), ('mAEtzyt', 'mAEtzyt', 'NN'), ('brbEt', 'brbEt', 'NN'), ('y', 'y', 'SPRP'), ('wAnA', 'wAnA', 'PRP'), ('lHAly', 'lHAly', 'JJ'), ('lw', 'lw', 'IN'), ('EzAwyhm', 'EzAwyhm', 'PRP'), ('t', 't', 'TNS'), ('zyH', 'zyH', 'VB'), ('Alhm', 'Alhm', 'NN'), ('Eny', 'Eny', 'NNP'), ('EArfn', 'EArfn', 'JJ'), ('nfs', 'nfs', 'NN'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('EArf', 'EArf', 'VB'), ('mn', 'mn', 'IN'), ('qbAl', 'qbAl', 'NN'), ('y', 'y', 'SPRP'), ('$ltn', '$ltn', 'NN'), ('mAhyDp', 'mAhyDp', 'NN'), ('bAl', 'bAl', 'NN'), ('Almgny', 'Almgny', 'NNP'), ('DQUOTE', 'DQUOTE', 'DQUOTE')]).

sentence([('lA', 'lA', 'VB'), ('b>s', 'b>s', 'NN'), ('bqlylK', 'bqlylK', 'NN'), ('mn', 'mn', 'IN'), ('Al', 'Al', 'ART'), ('xyb', 'xyb', 'NN'), ('At', 'At', 'AGR'), ('f', 'f', 'CC'), ('qd', 'qd', 'VB'), ('A', 'A', 'TNS'), ('Etdtu', 'Etdtu', 'VB'), ('ElY', 'ElY', 'IN'), ('گvyr', 'گvyr', 'NN'), ('hA', 'hA', 'SPRP'), ('.', '.', 'PUNC')]).

sentence([('@', '@', 'REP'), ('rakan_kuw', 'rakan_kuw', 'username'), ('slAm', 'slAm', 'NNP'), ('AlAx', 'AlAx', 'NN'), ('fhd', 'fhd', 'NNP'), ('A', 'A', 'TNS'), ('ryd', 'ryd', 'VB'), ('k', 'k', 'SPRP'), ('fy', 'fy', 'IN'), ('mwDwE', 'mwDwE', 'NN')]).

sentence([('@', '@', 'REP'), ('Afc__99', 'Afc__99', 'username'), ('@', '@', 'MEN'), ('tareq_almalaki', 'tareq_almalaki', 'username'), ('Allhm', 'Allhm', 'NN'), ('>myn', '>myn', 'NN')]).

sentence([('AsEd', 'AsEd', 'NNP'), ('qlb', 'qlb', 'NN'), ('y', 'y', 'SPRP'), ('yA', 'yA', 'VB'), ('Allh', 'Allh', 'NNP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('jEl', 'jEl', 'VB'), ('h', 'h', 'SPRP'), ('mElqA', 'mElqA', 'NN'), ('bk', 'bk', 'NNP'), ('❤', '❤', 'emoj')]).

sentence([('@', '@', 'REP'), ('Hpa_18', 'Hpa_18', 'username'), ('nAs', 'nAs', 'NN'), ('t', 't', 'TNS'), ('rfE', 'rfE', 'VB'), ('Al', 'Al', 'ART'), ('DgT', 'DgT', 'NN')]).

sentence([('@', '@', 'REP'), ('FARAHHH777', 'FARAHHH777', 'username'), ('@', '@', 'MEN'), ('parqmqdad', 'parqmqdad', 'username'), ('@', '@', 'MEN'), ('wr34ty55', 'wr34ty55', 'username'), ('@', '@', 'MEN'), ('noorraad_zahra', 'noorraad_zahra', 'username'), ('lA', 'lA', 'VB'), ('wAllh', 'wAllh', 'NNP'), ('hwmn', 'hwmn', 'NN'), ('EbdAlxAlq', 'EbdAlxAlq', 'NNP'), ('w$yly', 'w$yly', 'NNP'), ('Aydj', 'Aydj', 'NN'), ('mn', 'mn', 'IN'), ('gyr', 'gyr', 'NN'), ('zEl', 'zEl', 'NNP')]).

sentence([('slAm', 'slAm', 'NNP'), ('Elykm', 'Elykm', 'PRP'), ('w', 'w', 'CC'), ('rHm', 'rHm', 'VB'), ('h', 'h', 'SPRP'), ('Allh', 'Allh', 'NNP'), ('w', 'w', 'CC'), ('brk', 'brk', 'NN'), ('At', 'At', 'AGR'), ('h', 'h', 'SPRP'), ('hl', 'hl', 'WRP'), ('bAmk', 'bAmk', 'NN'), ('An', 'An', 'AGR'), ('br$l', 'br$l', 'NN'), ('wn', 'wn', 'AGR'), ('h', 'h', 'SPRP'), ('AntzAE', 'AntzAE', 'NN'), ('SdAr', 'SdAr', 'NN'), ('h', 'h', 'SPRP'), ('Al', 'Al', 'ART'), ('dwr', 'dwr', 'NN'), ('y', 'y', 'SPRP'), ('mn', 'mn', 'IN'), ('Al', 'Al', 'ART'), ('ryAl', 'ryAl', 'NN'), ('w', 'w', 'CC'), ('AntzAE', 'AntzAE', 'NN'), ('Al', 'Al', 'ART'), ('AbTAl', 'AbTAl', 'NN'), ('ٳ*A', 'ٳ*A', 'WRP'), ('tm', 'tm', 'VB'), ('tgyr', 'tgyr', 'NN'), ('Al', 'Al', 'ART'), ('mdrb', 'mdrb', 'NN')]).

sentence([('Allh', 'Allh', 'NNP'), ('y', 'y', 'TNS'), ('rHm', 'rHm', 'VB'), ('h', 'h', 'SPRP'), ('w', 'w', 'CC'), ('y', 'y', 'TNS'), ('rHm', 'rHm', 'VB'), ('Amw', 'Amw', 'NN'), ('At', 'At', 'AGR'), ('Al', 'Al', 'ART'), ('mslm', 'mslm', 'NN'), ('yn', 'yn', 'AGR'), ('w', 'w', 'CC'), ('y', 'y', 'TNS'), ('sk', 'sk', 'VB'), ('n', 'n', 'PERS'), ('h', 'h', 'SPRP'), ('f', 'f', 'CC'), ('s', 's', 'FUT'), ('yH', 'yH', 'VB'), ('jnAt', 'jnAt', 'NN'), ('h', 'h', 'SPRP'), ('.', '.', 'PUNC'), ('w', 'w', 'CC'), ('y', 'y', 'TNS'), ('EwD', 'EwD', 'VB'), ('Ahl', 'Ahl', 'NN'), ('h', 'h', 'SPRP'), ('bAlSbr', 'bAlSbr', 'NN'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('slw', 'slw', 'NN'), ('An', 'An', 'AGR'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC')]).

sentence([('Allh', 'Allh', 'NNP'), ('y', 'y', 'TNS'), ('hdy', 'hdy', 'VB'), ('k', 'k', 'SPRP'), ('y', 'y', 'TNS'), ('ADrs', 'ADrs', 'VB'), ('y', 'y', 'SPRP'), ('lys', 'lys', 'VB'), ('w', 'w', 'CC'), ('qtk', 'qtk', 'NN')]).

sentence([('@', '@', 'REP'), ('soooso693', 'soooso693', 'username'), ('w', 'w', 'CC'), ('qlt', 'qlt', 'NN'), ('y', 'y', 'SPRP'), ('hl', 'hl', 'WRP'), ('t', 't', 'TNS'), ('qSd', 'qSd', 'VB'), ('mjnwnp', 'mjnwnp', 'JJ'), ('AnA', 'AnA', 'PRP'), ('y', 'y', 'TNS'), ('En', 'En', 'VB'), ('y', 'y', 'SPRP'), ('AntK', 'AntK', 'NN'), ('Afkrp', 'Afkrp', 'NN'), ('Al', 'Al', 'ART'), ('jmyE', 'jmyE', 'NN'), ('mjAn', 'mjAn', 'NN'), ('yn', 'yn', 'AGR'), ('Ant', 'Ant', 'NN'), ('y', 'y', 'SPRP'), ('t', 't', 'TNS'), ('jrH', 'jrH', 'VB'), ('yn', 'yn', 'PERS'), ('Hq', 'Hq', 'VB'), ('A', 'A', 'PERS')]).

sentence([('srA', 'srA', 'NN'), ('Al', 'Al', 'ART'), ('lyl', 'lyl', 'NN'), ('w', 'w', 'CC'), ('Eywn', 'Eywn', 'NN'), ('Al', 'Al', 'ART'), ('hwAw', 'hwAw', 'NN'), ('y', 'y', 'SPRP'), ('ElY', 'ElY', 'IN'), ('Al', 'Al', 'ART'), ('jwAl', 'jwAl', 'NN'), ('lEl', 'lEl', 'VB'), ('wEsY', 'wEsY', 'RB'), ('y', 'y', 'TNS'), ('Aty', 'Aty', 'VB'), ('h', 'h', 'SPRP'), ('Elmn', 'Elmn', 'NNP'), ('y', 'y', 'TNS'), ('b$r', 'b$r', 'VB'), ('bh', 'bh', 'PRP'), ('y', 'y', 'TNS'), ('sj', 'sj', 'VB'), ('AlxyAl', 'AlxyAl', 'NNP'), ('w', 'w', 'CC'), ('y', 'y', 'TNS'), ('zEj', 'zEj', 'VB'), ('Al', 'Al', 'ART'), ('Swt', 'Swt', 'NN'), ('bAlmwAl', 'bAlmwAl', 'NN'), ('br', 'br', 'VB'), ('t', 't', 'PERS'), ('HAl', 'HAl', 'NN'), ('h', 'h', 'SPRP'), ('Al', 'Al', 'ART'), ('frqA', 'frqA', 'NN'), ('w', 'w', 'CC'), ('$fh', '$fh', 'NN'), ('ElY', 'ElY', 'IN'), ('qrb', 'qrb', 'NN'), ('h', 'h', 'SPRP'), ('DQUOTE', 'DQUOTE', 'DQUOTE')]).

sentence([('@', '@', 'REP'), ('mahdi_bukhari', 'mahdi_bukhari', 'username'), ('wmqdryn', 'wmqdryn', 'JJ'), ('jhwdkw', 'jhwdkw', 'NN'), ('wAllh', 'wAllh', 'NNP'), ('y', 'y', 'TNS'), ('sEd', 'sEd', 'VB'), ('km', 'km', 'SPRP')]).

sentence([('$wf', '$wf', 'NNP'), ('Al', 'Al', 'ART'), ('jbl', 'jbl', 'NN'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('qf', 'qf', 'VB'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('hz', 'hz', 'VB'), ('t', 't', 'PERS'), ('h', 'h', 'SPRP'), ('ryH', 'ryH', 'NN'), ('$wf', '$wf', 'NNP'), ('Alqmr', 'Alqmr', 'NNP'), ('EAly', 'EAly', 'NNP'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('y', 'y', 'TNS'), ('mk', 'mk', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'TNS'), ('TyH', 'TyH', 'VB'), ('AhdAG', 'AhdAG', 'NN'), ('lmn', 'lmn', 'IN'), ('A', 'A', 'TNS'), ('frH', 'frH', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('kvyrA', 'kvyrA', 'JJ'), ('w', 'w', 'CC'), ('t', 't', 'TNS'), ('$rbt', '$rbt', 'VB'), ('Hb', 'Hb', 'NN'), ('AlzEym', 'AlzEym', 'NNP'), ('bwjwd', 'bwjwd', 'NN'), ('h', 'h', 'SPRP'), ('@', '@', 'PUNC'), ('http://t.co/HuKoTp7Lo0', 'http://t.co/HuKoTp7Lo0', 'link')]).

sentence([('★', '★', 'emoj'), ('★', '★', 'emoj'), ('☆', '☆', 'emoj'), ('☆', '☆', 'emoj'), ('★', '★', 'emoj'), ('@', '@', 'MEN'), ('BankAljazira', 'BankAljazira', 'username'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('>shl', '>shl', 'JJ'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('bTAqp', 'bTAqp', 'NN'), ('nAdyk', 'nAdyk', 'NNP'), ('mn', 'mn', 'IN'), ('bnk', 'bnk', 'NN'), ('Aljzyrp', 'Aljzyrp', 'NNP'), ('tqdm', 'tqdm', 'NN'), ('bTlb', 'bTlb', 'NN'), ('k', 'k', 'SPRP'), ('Al|n', 'Al|n', 'NN'), ('http://t.co/M7je55XkcV', 'http://t.co/M7je55XkcV', 'link'), ('http://t.co/cUrksqYlAE.Ktb', 'http://t.co/cUrksqYlAE.Ktb', 'link'), ('13', '13', 'CD')]).

sentence([('Al', 'Al', 'ART'), ('nsy', 'nsy', 'NN'), ('An', 'An', 'AGR'), ('bAlnsy', 'bAlnsy', 'NN'), ('An', 'An', 'AGR'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('bEd', 'bEd', 'NN'), ('bAlbEd', 'bAlbEd', 'NN'), ('wAnA', 'wAnA', 'PRP'), ('l', 'l', 'IN'), ('nfs', 'nfs', 'NN'), ('y', 'y', 'SPRP'), ('COMMA', 'COMMA', 'COMMA'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('nt', 'nt', 'VB'), ('l>mvAlk', 'l>mvAlk', 'RB'), ('!', '!', 'PUNC')]).

sentence([(':', ':', 'PUNC'), ('mn', 'mn', 'IN'), ('>wq', '>wq', 'NN'), ('At', 'At', 'AGR'), ('Al', 'Al', 'ART'), ('<jAbp', '<jAbp', 'NN'), ('fy', 'fy', 'IN'), ('jmyE', 'jmyE', 'NNP'), ('Al', 'Al', 'ART'), ('Slw', 'Slw', 'NN'), ('At', 'At', 'AGR'), ('f', 'f', 'CC'), ('rD', 'rD', 'VB'), ('hA', 'hA', 'SPRP'), ('w', 'w', 'CC'), ('n', 'n', 'TNS'), ('fl', 'fl', 'VB'), ('hA', 'hA', 'SPRP'), (':', ':', 'PUNC'), ('HAl', 'HAl', 'NN'), ('Al', 'Al', 'ART'), ('sjwd', 'sjwd', 'NN'), ('l', 'l', 'IN'), ('qwl', 'qwl', 'NN'), ('h', 'h', 'SPRP'), ('ﷺ', 'ﷺ', 'WRP'), (':', ':', 'PUNC'), ('«', '«', 'WRP'), ('>qrb', '>qrb', 'VB'), ('mA', 'mA', 'NN'), ('ykwn', 'ykwn', 'NN'), ('AlEbd', 'AlEbd', 'NNP'), ('mn', 'mn', 'IN'), ('rbh', 'rbh', 'NN'), ('whw', 'whw', 'PRP'), ('sAjd', 'sAjd', 'NNP'), ('f', 'f', 'CC'), ('>kvr', '>kvr', 'VB'), ('wA', 'wA', 'PERS'), ('Al', 'Al', 'ART'), ('dEAG', 'dEAG', 'NN'), ('»', '»', 'WRP'), ('rwA', 'rwA', 'NN'), ('h', 'h', 'SPRP'), ('mslm', 'mslm', 'NNP'), ('DQUOTE', 'DQUOTE', 'DQUOTE')]).

sentence([('mhmaA', 'mhmaA', 'NN'), ('A', 'A', 'TNS'), ('ntZr', 'ntZr', 'VB'), ('nA', 'nA', 'SPRP'), ('COMMA', 'COMMA', 'COMMA'), ('fa', 'fa', 'NN'), ('Al', 'Al', 'ART'), ('<ntZAru', '<ntZAru', 'NN'), ('mujr~d', 'mujr~d', 'NN'), ('t', 't', 'TNS'), ('Eab', 'Eab', 'VB')]).

sentence([('DQUOTE', 'DQUOTE', 'DQUOTE'), ('@', '@', 'RET'), ('Dr_almosleh:', 'Dr_almosleh:', 'username'), ('xTwrp', 'xTwrp', 'NN'), ('Al', 'Al', 'ART'), ('tjr&', 'tjr&', 'NN'), ('ElY', 'ElY', 'IN'), ('Al', 'Al', 'ART'), ('ftwY', 'ftwY', 'NN'), ('{', '{', 'WRP'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('t', 't', 'TNS'), ('qf', 'qf', 'VB'), ('mA', 'mA', 'NN'), ('lys', 'lys', 'VB'), ('lk', 'lk', 'PRP'), ('bh', 'bh', 'PRP'), ('Elm', 'Elm', 'NNP'), ('<n', '<n', 'IN'), ('Al', 'Al', 'ART'), ('smE', 'smE', 'NN'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('bSr', 'bSr', 'NN'), ('wAlf&Ad', 'wAlf&Ad', 'NNP'), ('kl', 'kl', 'NN'), ('>wl}', '>wl}', 'VB'), ('k', 'k', 'SPRP'), ('kAn', 'kAn', 'NNP'), ('Enh', 'Enh', 'IN'), ('ms&wlA', 'ms&wlA', 'NN'), ('}', '}', 'NN'), ('http://t.co/gUfH3ovrC8', 'http://t.co/gUfH3ovrC8', 'link')]).

sentence([('@', '@', 'REP'), ('hammada_iraqi', 'hammada_iraqi', 'username'), ('@', '@', 'MEN'), ('United7Heart', 'United7Heart', 'username'), ('@', '@', 'MEN'), ('alshranei07', 'alshranei07', 'username'), ('lwlA', 'lwlA', 'IN'), ('mysy', 'mysy', 'JJ'), ('lmA', 'lmA', 'WP'), ('t', 't', 'TNS'), ('<hlt', '<hlt', 'VB'), ('Al', 'Al', 'ART'), ('Arjnt', 'Arjnt', 'NN'), ('yn', 'yn', 'AGR'), ('mn', 'mn', 'IN'), ('Al', 'Al', 'ART'), ('mjmwE', 'mjmwE', 'NN'), ('h', 'h', 'SPRP'), ('bAlAsAs', 'bAlAsAs', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('Ayn', 'Ayn', 'WP'), ('Anxyl', 'Anxyl', 'NNP'), ('fy', 'fy', 'IN'), ('dwr', 'dwr', 'NN'), ('Al', 'Al', 'ART'), ('mjmwE', 'mjmwE', 'NN'), ('At', 'At', 'AGR'), ('?', '?', 'PUNC')]).

sentence([('A', 'A', 'TNS'), ('kr', 'kr', 'VB'), ('h', 'h', 'SPRP'), ('Al', 'Al', 'ART'), ('$fq', '$fq', 'NN'), ('h', 'h', 'SPRP'), ('.', '.', 'PUNC')]).

sentence([('@', '@', 'REP'), ('EA__8', 'EA__8', 'username'), ('@', '@', 'MEN'), ('xlc_8', 'xlc_8', 'username')]).

sentence([('y', 'y', 'TNS'), ('Al', 'Al', 'VB'), ('h', 'h', 'SPRP'), ('t', 't', 'TNS'), ('Eb', 'Eb', 'VB')]).

sentence([('fyk', 'fyk', 'NNP'), ('AbtsAmp', 'AbtsAmp', 'NN'), ('Tfl', 'Tfl', 'NN'), ('w', 'w', 'CC'), ('nZrp', 'nZrp', 'NN'), ('mlAk', 'mlAk', 'NNP'), ('w', 'w', 'CC'), ('bAq', 'bAq', 'VB'), ('y', 'y', 'SPRP'), ('>wSAf', '>wSAf', 'NN'), ('k', 'k', 'SPRP'), ('llh', 'llh', 'NN'), ('Al', 'Al', 'ART'), ('Ejab', 'Ejab', 'NN')]).

sentence([('A*A', 'A*A', 'IN'), ('lm', 'lm', 'RP'), ('y', 'y', 'TNS'), ('tm', 'tm', 'VB'), ('Alrd', 'Alrd', 'NN'), ('xlAl', 'xlAl', 'NN'), ('24', '24', 'CD'), ('sAE', 'sAE', 'NN'), ('h', 'h', 'SPRP'), ('s', 's', 'FUT'), ('y', 'y', 'TNS'), ('tm', 'tm', 'VB'), ('tSEyd', 'tSEyd', 'NN'), ('Al', 'Al', 'ART'), ('mwDwE', 'mwDwE', 'NN'), ('l', 'l', 'IN'), ('lfyfA', 'lfyfA', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('byD', 'byD', 'NN'), ('Allh', 'Allh', 'NNP'), ('w', 'w', 'CC'), ('jhk', 'jhk', 'NN'), ('yA', 'yA', 'RP'), ('Abn', 'Abn', 'NNP'), ('sEd', 'sEd', 'NNP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('A', 'A', 'TNS'), ('qdH', 'qdH', 'VB'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('Hn', 'Hn', 'VB'), ('A', 'A', 'PERS'), ('w', 'w', 'CC'), ('rAk', 'rAk', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('Al', 'Al', 'ART'), ('$bAb', '$bAb', 'NN')]).

sentence([('@', '@', 'REP'), ('mahwie2', 'mahwie2', 'username'), ('@', '@', 'MEN'), ('AbdulmohsinHela', 'AbdulmohsinHela', 'username'), ('@', '@', 'MEN'), ('hanahan109', 'hanahan109', 'username'), ('A', 'A', 'TNS'), ('Et*r', 'Et*r', 'VB'), ('En', 'En', 'IN'), ('dxwly', 'dxwly', 'JJ'), ('fy', 'fy', 'IN'), ('mntSf', 'mntSf', 'NN'), ('Al', 'Al', 'ART'), ('Hdyv', 'Hdyv', 'NN'), ('s', 's', 'FUT'), ('rn', 'rn', 'VB'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('t', 't', 'TNS'), ('$rft', '$rft', 'VB'), ('bnqA$', 'bnqA$', 'NN'), ('km', 'km', 'SPRP')]).

sentence([('jAyb', 'jAyb', 'NN'), ('yn', 'yn', 'AGR'), ('fy', 'fy', 'IN'), ('Al', 'Al', 'ART'), ('tlyfzy', 'tlyfzy', 'NN'), ('wn', 'wn', 'AGR'), ('Al', 'Al', 'ART'), ('nAs', 'nAs', 'NN'), ('byrHb', 'byrHb', 'VB'), ('wA', 'wA', 'PERS'), ('bAlsysy', 'bAlsysy', 'JJ'), ('COMMA', 'COMMA', 'COMMA'), ('ASlA', 'ASlA', 'NN'), ('Al', 'Al', 'ART'), ('Tryq', 'Tryq', 'NN'), ('Al*y', 'Al*y', 'WP'), ('hw', 'hw', 'PRP'), ('m$', 'm$', 'VB'), ('y', 'y', 'SPRP'), ('mnh', 'mnh', 'NNP'), ('fy', 'fy', 'IN'), ('Algrdqp', 'Algrdqp', 'NNP'), ('mkAn$', 'mkAn$', 'NN'), ('fyh', 'fyh', 'PRP'), ('AlA', 'AlA', 'IN'), ('EsAkr', 'EsAkr', 'NN'), ('w', 'w', 'CC'), ('HAbsyn', 'HAbsyn', 'JJ'), ('Al', 'Al', 'ART'), ('nAs', 'nAs', 'NN'), ('fy', 'fy', 'IN'), ('Al', 'Al', 'ART'), ('$wArE', '$wArE', 'NN'), ('Al', 'Al', 'ART'), ('dAxlyp', 'dAxlyp', 'NN')]).

sentence([('AnA', 'AnA', 'PRP'), ('lw', 'lw', 'IN'), ('xATr', 'xATr', 'NN'), ('y', 'y', 'SPRP'), ('y', 'y', 'TNS'), ('qw~Y', 'qw~Y', 'VB'), ('tEdyt', 'tEdyt', 'NN'), ('k', 'k', 'SPRP'), ('.', '.', 'PUNC')]).

sentence([('@', '@', 'REP'), ('Maray99', 'Maray99', 'username'), ('@', '@', 'MEN'), ('atheernn', 'atheernn', 'username'), ('bEd', 'bEd', 'NN'), ('rwH', 'rwH', 'NNP'), ('Alsyd', 'Alsyd', 'NNP'), ('w', 'w', 'CC'), ('E$yr', 'E$yr', 'VB'), ('t', 't', 'PERS'), ('h', 'h', 'SPRP'), ('Ant', 'Ant', 'NN'), ('y', 'y', 'SPRP'), ('jt', 'jt', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('Al', 'Al', 'ART'), ('rAnj', 'rAnj', 'NN'), ('yA', 'yA', 'RP'), ('wld', 'wld', 'NN')]).

sentence([('http://t.co/mr4u3K5kkg', 'http://t.co/mr4u3K5kkg', 'link')]).

sentence([('(', '(', 'PUNC'), ('@', '@', 'PUNC'), ('m$Y', 'm$Y', 'VB'), ('hdy', 'hdy', 'NN'), ('h', 'h', 'SPRP'), (')', ')', 'NN'), ('https://t.co/6jAWFZ5q84', 'https://t.co/6jAWFZ5q84', 'link')]).

sentence([('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('sjd', 'sjd', 'VB'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('qtrb', 'qtrb', 'VB'), ('Almjr~p', 'Almjr~p', 'JJ'), ('Al', 'Al', 'ART'), ('Smt', 'Smt', 'NN'), ('fy', 'fy', 'IN'), ('Hrm', 'Hrm', 'NN'), ('Al', 'Al', 'ART'), ('jmAl', 'jmAl', 'NN'), ('jmAl', 'jmAl', 'NNP'), ('jzA', 'jzA', 'NN'), ('km', 'km', 'SPRP'), ('rby', 'rby', 'JJ'), ('Al', 'Al', 'ART'), ('frdws', 'frdws', 'NN')]).

sentence([('@', '@', 'REP'), ('RommanMohammad', 'RommanMohammad', 'username'), ('@', '@', 'MEN'), ('Hasan_Abuhashem', 'Hasan_Abuhashem', 'username'), ('t', 't', 'TNS'), ('mzEt', 'mzEt', 'VB'), ('l', 'l', 'IN'), ('drjp', 'drjp', 'NN'), ('Any', 'Any', 'JJ'), ('nfs', 'nfs', 'NN'), ('y', 'y', 'SPRP'), ('Sr', 'Sr', 'VB'), ('t', 't', 'PERS'), ('AxyT', 'AxyT', 'NN')]).

sentence([('Al', 'Al', 'ART'), ('wjE', 'wjE', 'NN'), ('yA', 'yA', 'RP'), ('SAHb', 'SAHb', 'NN'), ('y', 'y', 'SPRP'), ('A', 'A', 'TNS'), ('nk', 'nk', 'VB'), ('t', 't', 'TNS'), ('drs', 'drs', 'VB'), ('w', 'w', 'CC'), ('t', 't', 'TNS'), ('nsY', 'nsY', 'VB'), ('Al*y', 'Al*y', 'WP'), ('drst', 'drst', 'NN'), ('h', 'h', 'SPRP')]).

sentence([('bahagia', 'bahagia', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC')]).

sentence([('Al', 'Al', 'ART'), ('>tHAd', '>tHAd', 'NN'), ('y', 'y', 'TNS'), ('bHv', 'bHv', 'VB'), ('En', 'En', 'IN'), ('rEAp', 'rEAp', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('wfy', 'wfy', 'JJ'), ('nfs', 'nfs', 'NN'), ('Al', 'Al', 'ART'), ('wqt', 'wqt', 'NN'), ('hw', 'hw', 'PRP'), ('Al', 'Al', 'ART'), ('rAE', 'rAE', 'NN'), ('y', 'y', 'SPRP'), ('Al', 'Al', 'ART'), ('>kbr', '>kbr', 'NN'), ('(', '(', 'PUNC'), ('l', 'l', 'IN'), ('ljnp', 'ljnp', 'NN'), ('Al', 'Al', 'ART'), ('>nDbAT', '>nDbAT', 'NN'), (')', ')', 'NN'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('!', '!', 'PUNC'), ('!', '!', 'PUNC'), ('!', '!', 'PUNC')]).

sentence([('-', '-', 'PUNC'), ('yA', 'yA', 'RP'), ('qlb', 'qlb', 'NN'), ('A', 'A', 'TNS'), ('Hk', 'Hk', 'VB'), ('y', 'y', 'SPRP'), ('lh', 'lh', 'PRP'), ('A', 'A', 'TNS'), ('nk', 'nk', 'VB'), ('COMMA', 'COMMA', 'COMMA'), ('lA', 'lA', 'VB'), ('t', 't', 'TNS'), ('byN', 'byN', 'VB'), ('gyr', 'gyr', 'NN'), ('h', 'h', 'SPRP'), ('.', '.', 'PUNC')]).

sentence([('bnt', 'bnt', 'NNP'), ('qAl', 'qAl', 'VB'), ('t', 't', 'PERS'), ('l', 'l', 'IN'), ('>bw', '>bw', 'NN'), ('hA', 'hA', 'SPRP'), ('>by', '>by', 'NNP'), ('>drs', '>drs', 'VB'), ('brA', 'brA', 'NN'), ('qAl', 'qAl', 'VB'), (':', ':', 'PUNC'), ('lys', 'lys', 'VB'), ('m$kl', 'm$kl', 'NN'), ('h', 'h', 'SPRP'), ('klmy', 'klmy', 'NNP'), ('>mk', '>mk', 'NN'), ('t', 't', 'TNS'), ('fr$', 'fr$', 'VB'), ('lk', 'lk', 'PRP'), ('fy', 'fy', 'IN'), ('Al', 'Al', 'ART'), ('Hw$', 'Hw$', 'NN'), ('☜', '☜', 'emoj'), ('Al', 'Al', 'ART'), ('mhm', 'mhm', 'NN'), (':', ':', 'PUNC'), ('Al', 'Al', 'ART'), ('bnt', 'bnt', 'NN'), ('t', 't', 'TNS'), ('dwr', 'dwr', 'VB'), ('fy', 'fy', 'IN'), ('Al', 'Al', 'ART'), ('sTH', 'sTH', 'NN'), ('t', 't', 'TNS'), ('HAwl', 'HAwl', 'VB'), ('t', 't', 'TNS'), ('ntHr', 'ntHr', 'VB'), ('☺', '☺', 'emoj')]).

sentence([('@', '@', 'REP'), ('Rarrvine', 'Rarrvine', 'username'), ('@', '@', 'MEN'), ('Xunknownex', 'Xunknownex', 'username'), ('AnqlE', 'AnqlE', 'NN'), ('y', 'y', 'SPRP'), ('mwty', 'mwty', 'JJ')]).

sentence([('http://t.co/W1l7FfJ7Da', 'http://t.co/W1l7FfJ7Da', 'link')]).

sentence([('A', 'A', 'TNS'), ('Hb', 'Hb', 'VB'), ('k', 'k', 'SPRP'), ('Hb', 'Hb', 'NN'), ('mAl', 'mAl', 'NN'), ('h', 'h', 'SPRP'), ('Hdwd', 'Hdwd', 'NN'), ('wA*A', 'wA*A', 'IN'), ('fyh', 'fyh', 'PRP'), ('Hdwd', 'Hdwd', 'NN'), ('A', 'A', 'TNS'), ('Hb', 'Hb', 'VB'), ('k', 'k', 'SPRP'), ('thryb', 'thryb', 'NN'), ('DQUOTE', 'DQUOTE', 'DQUOTE'), ('̮', '̮', 'WRP'), ('*', '*', 'PUNC'), ('*', '*', 'PUNC')]).

sentence([('h*A', 'h*A', 'DT'), ('Al', 'Al', 'ART'), ('rwybDp', 'rwybDp', 'NN'), ('Al*y', 'Al*y', 'WP'), ('H*r', 'H*r', 'VB'), ('nA', 'nA', 'SPRP'), ('mnhm', 'mnhm', 'PRP'), ('rswl', 'rswl', 'NN'), ('Allh', 'Allh', 'NNP'), ('SlY', 'SlY', 'VB'), ('Allh', 'Allh', 'NNP'), ('Elyp', 'Elyp', 'NNP'), ('w', 'w', 'CC'), ('s', 's', 'FUT'), ('lm', 'lm', 'VB')]).

sentence([('@', '@', 'REP'), ('Eng_Maazalbasha', 'Eng_Maazalbasha', 'username'), ('yAx', 'yAx', 'NN'), ('AlwAHd', 'AlwAHd', 'NNP'), ('lA', 'lA', 'VB'), ('y', 'y', 'TNS'), ('hZr', 'hZr', 'VB'), ('dA', 'dA', 'NN'), ('$nw', '$nw', 'NN'), ('dA', 'dA', 'NN'), ('yAx', 'yAx', 'NN')]).

sentence([('http://t.co/gV0iyRG03M', 'http://t.co/gV0iyRG03M', 'link')]).

sentence([('★', '★', 'emoj'), ('★', '★', 'emoj'), ('☆', '☆', 'emoj'), ('☆', '☆', 'emoj'), ('★', '★', 'emoj'), ('@', '@', 'MEN'), ('BankAljazira', 'BankAljazira', 'username'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('>shl', '>shl', 'JJ'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('bTAqp', 'bTAqp', 'NN'), ('nAdyk', 'nAdyk', 'NNP'), ('mn', 'mn', 'IN'), ('bnk', 'bnk', 'NN'), ('Aljzyrp', 'Aljzyrp', 'NNP'), ('tqdm', 'tqdm', 'NN'), ('bTlb', 'bTlb', 'NN'), ('k', 'k', 'SPRP'), ('Al|n', 'Al|n', 'NN'), ('http://t.co/M7je55XkcV', 'http://t.co/M7je55XkcV', 'link'), ('http://t.co/cUrksqYlAE.Ktb', 'http://t.co/cUrksqYlAE.Ktb', 'link'), ('14', '14', 'CD')]).

sentence([('http://t.co/UIHJC4b5Dk', 'http://t.co/UIHJC4b5Dk', 'link')]).

sentence([('@', '@', 'REP'), ('alfaisal_ragad', 'alfaisal_ragad', 'username'), ('@', '@', 'MEN'), ('a_enaya', 'a_enaya', 'username'), ('Sdq', 'Sdq', 'VB'), ('t', 't', 'PERS'), ('yA', 'yA', 'RP'), ('bnt', 'bnt', 'NN'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('Hsb', 'Hsb', 'VB'), ('nA', 'nA', 'SPRP'), ('Allh', 'Allh', 'NNP'), ('w', 'w', 'CC'), ('nEm', 'nEm', 'NN'), ('Alwkyl', 'Alwkyl', 'NNP'), ('.', '.', 'PUNC')]).

sentence([('rHm', 'rHm', 'NN'), ('k', 'k', 'SPRP'), ('Al', 'Al', 'ART'), ('pyASAHb', 'pyASAHb', 'NN'), ('Al', 'Al', 'ART'), ('Ayd', 'Ayd', 'NN'), ('y', 'y', 'SPRP'), ('Al', 'Al', 'ART'), ('byDAGrHmpwAsEp', 'byDAGrHmpwAsEp', 'NN'), ('http://t.co/Hid7nVn0M7', 'http://t.co/Hid7nVn0M7', 'link')]).

sentence([('@', '@', 'REP'), ('sha3r_30', 'sha3r_30', 'username')]).

sentence([('knt', 'knt', 'NN'), ('A', 'A', 'TNS'), ('shr', 'shr', 'VB'), ('ElY', 'ElY', 'IN'), ('$An', '$An', 'NN'), ('A', 'A', 'TNS'), ('HAky', 'HAky', 'VB'), ('k', 'k', 'SPRP'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('ywm', 'ywm', 'NN'), ('kl', 'kl', 'NN'), ('mA', 'mA', 'NN'), ('>$tq', '>$tq', 'VB'), ('t', 't', 'PERS'), ('lk', 'lk', 'PRP'), ('n', 'n', 'TNS'), ('mt', 'mt', 'VB'), ('bdry', 'bdry', 'NNP'), ('DQUOTE', 'DQUOTE', 'DQUOTE')]).

sentence([('mzAjy', 'mzAjy', 'JJ'), ('Alywm', 'Alywm', 'NNP'), ('(', '(', 'PUNC'), ('Eyn', 'Eyn', 'NN'), ('y', 'y', 'SPRP'), ('Eyn', 'Eyn', 'NN'), ('y', 'y', 'SPRP'), ('nfs', 'nfs', 'NN'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('mnY', 'mnY', 'NN'), ('Eyn', 'Eyn', 'NN'), ('y', 'y', 'SPRP'), (')', ')', 'NN'), ('Eyn', 'Eyn', 'NN'), ('y', 'y', 'SPRP'), ('AgAn', 'AgAn', 'NN'), ('y', 'y', 'SPRP'), ('Hb', 'Hb', 'NN'), ('mSr', 'mSr', 'NNP'), ('klyb', 'klyb', 'NNP'), ('rqSny…', 'rqSny…', 'NN'), ('http://t.co/GyCs1m5Vtz', 'http://t.co/GyCs1m5Vtz', 'link')]).

sentence([('@', '@', 'REP'), ('alhurranews', 'alhurranews', 'username'), ('@', '@', 'MEN'), ('M3399M', 'M3399M', 'username'), ('@', '@', 'MEN'), ('MohammedAssaf89', 'MohammedAssaf89', 'username'), ('@', '@', 'MEN'), ('shugairi', 'shugairi', 'username'), ('l', 'l', 'IN'), ('jyn', 'jyn', 'NN'), ('Al', 'Al', 'ART'), ('h*lwl', 'h*lwl', 'NN'), ('Akyd', 'Akyd', 'JJ')]).

sentence([('@', '@', 'REP'), ('MBC8PM', 'MBC8PM', 'username'), ('tbryr', 'tbryr', 'NN'), ('sxyf', 'sxyf', 'JJ'), ('mn', 'mn', 'IN'), ('rjl', 'rjl', 'NN'), ('>sxf', '>sxf', 'VB')]).

sentence([('Alywm', 'Alywm', 'NNP'), ('AlEAlmy', 'AlEAlmy', 'JJ'), ('l', 'l', 'IN'), ('lgp', 'lgp', 'NN'), ('Al', 'Al', 'ART'), ('Erbyp', 'Erbyp', 'NN'), ('lgp', 'lgp', 'NN'), ('Al', 'Al', 'ART'), ('qrAn', 'qrAn', 'NN'), ('Alkrym', 'Alkrym', 'NNP'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('>glby', '>glby', 'NN'), ('h', 'h', 'SPRP'), ('lA', 'lA', 'VB'), ('y', 'y', 'TNS'), ('jyd', 'jyd', 'VB'), ('wn', 'wn', 'PERS'), ('tlk', 'tlk', 'DT'), ('Al', 'Al', 'ART'), ('lgp', 'lgp', 'NN'), ('bTlAq', 'bTlAq', 'NN'), ('h', 'h', 'SPRP'), ('t', 't', 'TNS'), ('Am', 'Am', 'VB'), ('h', 'h', 'SPRP'), ('wAnA', 'wAnA', 'PRP'), ('mnhm', 'mnhm', 'PRP'), ('wmA', 'wmA', 'WP'), ('A', 'A', 'TNS'), ('nkr', 'nkr', 'VB')]).

sentence([('kl', 'kl', 'NN'), ('Hdyv', 'Hdyv', 'NN'), ('mErD', 'mErD', 'NN'), ('l', 'l', 'IN'), ('swG', 'swG', 'NN'), ('Al', 'Al', 'ART'), ('fhm', 'fhm', 'NN'), ('HtY', 'HtY', 'IN'), ('Al', 'Al', 'ART'), ('Smt', 'Smt', 'NN'), ('qd', 'qd', 'VB'), ('y', 'y', 'TNS'), ('sAG', 'sAG', 'VB'), ('f', 'f', 'CC'), ('hmh', 'hmh', 'NN'), ('!', '!', 'PUNC')]).

sentence([('fy', 'fy', 'IN'), ('bEZ', 'bEZ', 'NN'), ('Al', 'Al', 'ART'), ('mlAqyf', 'mlAqyf', 'NN'), ('mAly', 'mAly', 'NNP'), ('l', 'l', 'IN'), ('zwm', 'zwm', 'NN'), ('y', 'y', 'TNS'), ('Alyt', 'Alyt', 'VB'), ('bEZ', 'bEZ', 'NN'), ('AnAs', 'AnAs', 'NN'), ('t', 't', 'TNS'), ('str', 'str', 'VB'), ('h', 'h', 'SPRP'), ('hdwm', 'hdwm', 'NN'), ('h', 'h', 'SPRP')]).

sentence([('@', '@', 'REP'), ('A7MD_ic', 'A7MD_ic', 'username'), ('lys', 'lys', 'VB'), ('slTAn', 'slTAn', 'NNP'), ('Al*y', 'Al*y', 'WP'), ('bAlysAr', 'bAlysAr', 'NN'), ('?', '?', 'PUNC')]).

sentence([('Al*yn', 'Al*yn', 'WP'), ('rHl', 'rHl', 'VB'), ('wA', 'wA', 'PERS'), ('fy', 'fy', 'IN'), ('sn', 'sn', 'NN'), ('mbkrp', 'mbkrp', 'JJ'), ('>hdw', '>hdw', 'VB'), ('nA', 'nA', 'SPRP'), ('rsAlp', 'rsAlp', 'NN'), ('tqwl', 'tqwl', 'NN'), (':', ':', 'PUNC'), ('lA', 'lA', 'VB'), ('t', 't', 'TNS'), ('TylwA', 'TylwA', 'VB'), ('qwA}m', 'qwA}m', 'NN'), ('>mny', '>mny', 'NN'), ('At', 'At', 'AGR'), ('km', 'km', 'SPRP'), ('f', 'f', 'CC'), ('Al', 'Al', 'ART'), ('HyAp', 'HyAp', 'NN'), ('qSyrp', 'qSyrp', 'JJ'), ('COMMA', 'COMMA', 'COMMA'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('Eml', 'Eml', 'VB'), ('wA', 'wA', 'PERS'), ('l', 'l', 'IN'), ('|xrp', '|xrp', 'NN'), ('fhy', 'fhy', 'PRP'), ('Al', 'Al', 'ART'), ('dAr', 'dAr', 'NN'), ('AlbAqyp', 'AlbAqyp', 'JJ'), ('.', '.', 'PUNC')]).

sentence([('★', '★', 'emoj'), ('★', '★', 'emoj'), ('☆', '☆', 'emoj'), ('☆', '☆', 'emoj'), ('★', '★', 'emoj'), ('@', '@', 'MEN'), ('BankAljazira', 'BankAljazira', 'username'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('>shl', '>shl', 'JJ'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('bTAqp', 'bTAqp', 'NN'), ('nAdyk', 'nAdyk', 'NNP'), ('mn', 'mn', 'IN'), ('bnk', 'bnk', 'NN'), ('Aljzyrp', 'Aljzyrp', 'NNP'), ('tqdm', 'tqdm', 'NN'), ('bTlb', 'bTlb', 'NN'), ('k', 'k', 'SPRP'), ('Al|n', 'Al|n', 'NN'), ('http://t.co/M7je55XkcV', 'http://t.co/M7je55XkcV', 'link'), ('http://t.co/cUrksqYlAE.Ktb', 'http://t.co/cUrksqYlAE.Ktb', 'link'), ('15', '15', 'CD')]).

sentence([('byAn', 'byAn', 'NNP'), ('nAd', 'nAd', 'NN'), ('y', 'y', 'SPRP'), ('Al', 'Al', 'ART'), ('hlAl', 'hlAl', 'NN'), ('bEd', 'bEd', 'NN'), ('Edp', 'Edp', 'JJ'), ('tjArb', 'tjArb', 'NN'), ('y', 'y', 'TNS'), ('nTbq', 'nTbq', 'VB'), ('Elb', 'Elb', 'NN'), ('h', 'h', 'SPRP'), ('.', '.', 'PUNC'), ('zEm', 'zEm', 'VB'), ('Al', 'Al', 'ART'), ('frzdq', 'frzdq', 'NN'), ('An', 'An', 'VB'), ('s', 's', 'FUT'), ('y', 'y', 'TNS'), ('qtl', 'qtl', 'VB'), ('mrbE|', 'mrbE|', 'NN'), ('f', 'f', 'CC'), ('>b$r', '>b$r', 'VB'), ('bTwl', 'bTwl', 'NN'), ('slAmp', 'slAmp', 'NN'), ('yA', 'yA', 'RP'), ('mrbE', 'mrbE', 'NN'), ('.', '.', 'PUNC'), ('w', 'w', 'CC'), ('gd|', 'gd|', 'NN'), ('s', 's', 'FUT'), ('y', 'y', 'TNS'), ('tE$ی', 'tE$ی', 'VB'), ('AlHmydAny', 'AlHmydAny', 'NNP'), ('mE', 'mE', 'NN'), ('Al', 'Al', 'ART'), ('mrysl', 'mrysl', 'NN')]).

sentence([('@', '@', 'REP'), ('alahmadi1_b', 'alahmadi1_b', 'username'), ('lyh', 'lyh', 'NN'), ('qAl', 'qAl', 'VB'), ('wA', 'wA', 'PERS'), ('lk', 'lk', 'PRP'), ('Hqyn', 'Hqyn', 'NN'), ('Al', 'Al', 'ART'), ('$wrmA', '$wrmA', 'NN'), ('mAEnd', 'mAEnd', 'NN'), ('hm', 'hm', 'SPRP'), ('<HsAs', '<HsAs', 'WRP'), ('!', '!', 'PUNC'), ('?', '?', 'PUNC')]).

sentence([('Al*y', 'Al*y', 'WP'), ('t', 't', 'TNS'), ('ntZr', 'ntZr', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('t', 't', 'TNS'), ('Etbr', 'Etbr', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('fArs', 'fArs', 'NNP'), ('AHlAm', 'AHlAm', 'NN'), ('hA', 'hA', 'SPRP'), ('t', 't', 'TNS'), ('rA', 'rA', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('mDyE', 'mDyE', 'NN'), ('Al', 'Al', 'ART'), ('HSAn', 'HSAn', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('l>n', 'l>n', 'IN'), ('k*A', 'k*A', 'RB'), ('t', 't', 'TNS'), ('>xrt', '>xrt', 'VB'), ('hl', 'hl', 'RP'), ('t', 't', 'TNS'), ('xAf', 'xAf', 'VB'), ('?', '?', 'PUNC'), ('-', '-', 'PUNC'), ('nEm', 'nEm', 'NN'), ('>xAf', '>xAf', 'NN'), ('.', '.', 'PUNC'), ('mn', 'mn', 'IN'), ('mA*A', 'mA*A', 'WRP'), ('?', '?', 'PUNC'), ('-', '-', 'PUNC'), ('mn', 'mn', 'IN'), ('>n', '>n', 'IN'), ('t', 't', 'TNS'), ('kw', 'kw', 'VB'), ('n', 'n', 'PERS'), ('SlAt', 'SlAt', 'NN'), ('y', 'y', 'SPRP'), ('Alty', 'Alty', 'WP'), ('>Sl~y', '>Sl~y', 'NN'), ('hA', 'hA', 'SPRP'), ('~', '~', 'NN'), ('lys', 'lys', 'VB'), ('t', 't', 'PERS'), ('kmA', 'kmA', 'CC'), ('>rAd', '>rAd', 'NN'), ('hA', 'hA', 'SPRP'), ('Allh', 'Allh', 'NNP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('"', '"', 'NN')]).

sentence([('SEb', 'SEb', 'VB'), ('t', 't', 'TNS'), ('frD', 'frD', 'VB'), ('nfs', 'nfs', 'NN'), ('k', 'k', 'SPRP'), ('ElY', 'ElY', 'IN'), ('AHd', 'AHd', 'NN'), ('HtY', 'HtY', 'IN'), ('lw', 'lw', 'IN'), ('knt', 'knt', 'NN'), ('mA', 'mA', 'NN'), ('t', 't', 'TNS'), ('qdr', 'qdr', 'VB'), ('t', 't', 'TNS'), ('kml', 'kml', 'VB'), ('y', 'y', 'TNS'), ('wm', 'wm', 'VB'), ('k', 'k', 'SPRP'), ('bdwn', 'bdwn', 'NN'), ('h', 'h', 'SPRP'), ('COMMA', 'COMMA', 'COMMA'), ('lkn', 'lkn', 'CC'), ('A', 'A', 'TNS'), ('lA', 'lA', 'VB'), ('hm', 'hm', 'SPRP'), ('t', 't', 'TNS'), ('bEd', 'bEd', 'VB'), ('A*A', 'A*A', 'IN'), ('mA', 'mA', 'NN'), ('lqy', 'lqy', 'VB'), ('t', 't', 'PERS'), ('lk', 'lk', 'PRP'), ('qym', 'qym', 'NN'), ('h', 'h', 'SPRP'), ('End', 'End', 'NN'), ('h', 'h', 'SPRP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC')]).

sentence([('@', '@', 'REP'), ('salman_67890', 'salman_67890', 'username'), ('@', '@', 'MEN'), ('saudiinusa', 'saudiinusa', 'username'), ('ywnyfrysts', 'ywnyfrysts', 'NN'), ('hwtyl', 'hwtyl', 'NN')]).

sentence([('mTlwb', 'mTlwb', 'NN'), ('mndwb', 'mndwb', 'NN'), ('At', 'At', 'AGR'), ('tswyq', 'tswyq', 'NN'), ('bAlmnTqp', 'bAlmnTqp', 'NN'), ('Al', 'Al', 'ART'), ('$rqy', '$rqy', 'NN'), ('h', 'h', 'SPRP'), ('l', 'l', 'IN'), ('$rkp', '$rkp', 'NN'), ('dEAyp', 'dEAyp', 'NN'), ('w', 'w', 'CC'), ('AEl', 'AEl', 'NN'), ('An', 'An', 'AGR'), ('mqrhAmlkp', 'mqrhAmlkp', 'JJ'), ('AlbHryn', 'AlbHryn', 'NNP'), ('bAlrAtb', 'bAlrAtb', 'NNP'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('Emwl', 'Emwl', 'NN'), ('h', 'h', 'SPRP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('https://t.co/qfriKiOL4Z', 'https://t.co/qfriKiOL4Z', 'link'), ('AlsEwdyp', 'AlsEwdyp', 'NNP'), ('AldmAm', 'AldmAm', 'NNP')]).

sentence([('kl', 'kl', 'NN'), ('$xS', '$xS', 'NN'), ('y', 'y', 'TNS'), ('Zn', 'Zn', 'VB'), ('b>n', 'b>n', 'IN'), ('qlb', 'qlb', 'NN'), ('h', 'h', 'SPRP'), ('hw', 'hw', 'PRP'), ('>kvr', '>kvr', 'VB'), ('byAD', 'byAD', 'NN'), ('AF', 'AF', 'AC'), ('f', 'f', 'CC'), ('lntr', 'lntr', 'VB'), ('k', 'k', 'SPRP'), ('Al', 'Al', 'ART'), ('Znwn', 'Znwn', 'NN'), ('jAnbAF', 'jAnbAF', 'JJ'), ('w', 'w', 'CC'), ('lnrY', 'lnrY', 'VB'), ('>l>fEAl', '>l>fEAl', 'NN')]).

sentence([('qyf', 'qyf', 'NN'), ('|wAy', '|wAy', 'NNP'), ('sryE', 'sryE', 'JJ'), ('ElY', 'ElY', 'IN'), ('10', '10', 'CD'), ('|lAf', '|lAf', 'NN'), ('k', 'k', 'IN'), ('wynz', 'wynz', 'NN'), ('!', '!', 'PUNC'), ('https://t.co/x0U0vz20xy', 'https://t.co/x0U0vz20xy', 'link'), ('Al', 'Al', 'ART'), ('sHb', 'sHb', 'NN'), ('?', '?', 'PUNC'), ('bEd', 'bEd', 'NN'), ('dqyq', 'dqyq', 'NN'), ('h', 'h', 'SPRP'), ('!', '!', 'PUNC')]).

sentence([('@', '@', 'REP'), ('3boodSKH', '3boodSKH', 'username'), ('hy', 'hy', 'PRP'), ('lA', 'lA', 'VB'), ('t', 't', 'TNS'), ('jn', 'jn', 'VB'), ('y', 'y', 'SPRP')]).

sentence([('@', '@', 'REP'), ('fahad_uae2', 'fahad_uae2', 'username'), ('@', '@', 'MEN'), ('saeed_alsyari', 'saeed_alsyari', 'username'), ('w', 'w', 'CC'), ('Ant', 'Ant', 'NN'), ('y', 'y', 'SPRP'), ('bxyr', 'bxyr', 'NN'), ('!', '!', 'PUNC'), ('!', '!', 'PUNC'), ('!', '!', 'PUNC'), ('!', '!', 'PUNC'), ('!', '!', 'PUNC'), ('h', 'h', 'WRB'), ('fhd', 'fhd', 'NNP'), ('SHSH', 'SHSH', 'NNP'), ('kl', 'kl', 'NN'), ('EAm', 'EAm', 'NN'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('nt', 'nt', 'VB'), ('bxyr', 'bxyr', 'NN'), ('bwEskwr', 'bwEskwr', 'NN'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('Emr', 'Emr', 'NN'), ('klh', 'klh', 'NN'), ('An', 'An', 'VB'), ('$AG', '$AG', 'VB'), ('Allh', 'Allh', 'NNP')]).

sentence([('Hyn', 'Hyn', 'NN'), ('t', 't', 'TNS'), ('Ey$', 'Ey$', 'VB'), ('Al', 'Al', 'ART'), ('$Ewb', '$Ewb', 'NN'), ('dwAmp', 'dwAmp', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('mn', 'mn', 'IN'), ('Al', 'Al', 'ART'), ('Hrwb', 'Hrwb', 'NN'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('AnksAr', 'AnksAr', 'NN'), ('At', 'At', 'AGR'), ('t', 't', 'TNS'), ('SbH', 'SbH', 'VB'), ('fy', 'fy', 'IN'), ('Al', 'Al', 'ART'), ('mHSlp', 'mHSlp', 'NN'), ('*Akrp', '*Akrp', 'NN'), ('Al', 'Al', 'ART'), ('mwt', 'mwt', 'NN'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('lEjb', 'lEjb', 'VB'), ('!', '!', 'PUNC'), ('?', '?', 'PUNC')]).

sentence([('t', 't', 'TNS'), ('dr', 'dr', 'VB'), ('y', 'y', 'SPRP'), ('A', 'A', 'TNS'), ('nk', 'nk', 'VB'), ('End', 'End', 'NN'), ('y', 'y', 'SPRP'), ('AglA', 'AglA', 'NN'), ('mn', 'mn', 'IN'), ('AlgAly', 'AlgAly', 'JJ'), ('w', 'w', 'CC'), ('zwd', 'zwd', 'VB'), ('wAn', 'wAn', 'IN'), ('lk', 'lk', 'PRP'), ('f', 'f', 'CC'), ('Al', 'Al', 'ART'), ('qlb', 'qlb', 'NN'), ('jr~h', 'jr~h', 'DT'), ('COMMA', 'COMMA', 'COMMA'), ('wlk', 'wlk', 'PRP'), ('mATA', 'mATA', 'NN'), ('qdm', 'qdm', 'NN'), ('jEl', 'jEl', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('mA*wq', 'mA*wq', 'NN'), ('Hzn', 'Hzn', 'NN'), ('k', 'k', 'SPRP'), ('COMMA', 'COMMA', 'COMMA'), ('w', 'w', 'CC'), ('jEl', 'jEl', 'VB'), ('k', 'k', 'SPRP'), ('f', 'f', 'CC'), ('A', 'A', 'TNS'), ('lwjwd', 'lwjwd', 'VB'), ('w', 'w', 'CC'), ('jEl', 'jEl', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('mAEtAD', 'mAEtAD', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('xlA', 'xlA', 'NN'), ('w', 'w', 'CC'), ('lA', 'lA', 'VB'), ('Edm', 'Edm', 'NN')]).

sentence([('AlHb', 'AlHb', 'NN'), ('lys', 'lys', 'VB'), ('>n', '>n', 'IN'), ('t', 't', 'TNS'), ('HAdv', 'HAdv', 'VB'), ('n', 'n', 'PERS'), ('y', 'y', 'SPRP'), ('HynmA', 'HynmA', 'NN'), ('t', 't', 'TNS'), ('kw', 'kw', 'VB'), ('n', 'n', 'PERS'), ('mtfr~gFA', 'mtfr~gFA', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('bl', 'bl', 'CC'), ('>n', '>n', 'IN'), ('t', 't', 'TNS'), ('SnE', 'SnE', 'VB'), ('Al', 'Al', 'ART'), ('frAg', 'frAg', 'NN'), ('mn', 'mn', 'IN'), ('>jl', '>jl', 'VB'), ('mHAdvt', 'mHAdvt', 'NN'), ('y', 'y', 'SPRP'), ('fy', 'fy', 'IN'), ('Ez', 'Ez', 'NN'), ('<n$gAlk', '<n$gAlk', 'RB'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('"', '"', 'NN')]).

sentence([('http://t.co/11Wbz0W4oi', 'http://t.co/11Wbz0W4oi', 'link')]).

sentence([('AxlAq', 'AxlAq', 'NN'), ('AslAmyp', 'AslAmyp', 'NN'), ('>s}lp', '>s}lp', 'NN'), ('AxtbAr', 'AxtbAr', 'NN'), ('At', 'At', 'AGR'), ('http://t.co/WT3HOgsww7', 'http://t.co/WT3HOgsww7', 'link'), ('As}lp', 'As}lp', 'NN'), ('Al', 'Al', 'ART'), ('ktAb', 'ktAb', 'NN'), ('mHlwl', 'mHlwl', 'JJ'), ('http://t.co/ytIteR5nr1', 'http://t.co/ytIteR5nr1', 'link'), ('twDyH', 'twDyH', 'NN'), ('mn', 'mn', 'IN'), ('A', 'A', 'TNS'), ('xt', 'xt', 'VB'), ('k', 'k', 'SPRP'), ('$jwn', '$jwn', 'NN'), ('http://t.co/YnCqAx03X0', 'http://t.co/YnCqAx03X0', 'link')]).

sentence([('"', '"', 'NN'), ('@', '@', 'PUNC'), (':', ':', 'PUNC'), ('kwt', 'kwt', 'NNP'), ('twyt', 'twyt', 'NN'), ('wkm', 'wkm', 'PRP'), ('mEdl', 'mEdl', 'NN'), ('k', 'k', 'SPRP'), ('GPA', 'GPA', 'NN'), ('☝', '☝', 'emoj'), ('️"', '️"', 'WRP'), ('.', '.', 'PUNC'), ('5', '5', 'CD')]).

sentence([('mtAbE', 'mtAbE', 'NN'), ('w', 'w', 'CC'), ('mbswT', 'mbswT', 'VB'), ('Ak$n', 'Ak$n', 'NN'), ('yAdwry', 'yAdwry', 'JJ'), ('http://t.co/P3QY0JSOwG', 'http://t.co/P3QY0JSOwG', 'link')]).

sentence([('@', '@', 'REP'), ('all3ssaf', 'all3ssaf', 'username'), ('mmtAz', 'mmtAz', 'JJ'), ('COMMA', 'COMMA', 'COMMA'), ('COMMA', 'COMMA', 'COMMA'), ('jAhz', 'jAhz', 'JJ'), ('wAlA', 'wAlA', 'RP'), ('l', 'l', 'IN'), ('lHyn', 'lHyn', 'NN'), ('Al$AHn', 'Al$AHn', 'JJ')]).

sentence([('A', 'A', 'TNS'), ('Sl', 'Sl', 'VB'), ('hA', 'hA', 'SPRP'), ('lmA', 'lmA', 'WP'), ('btftHl', 'btftHl', 'NN'), ('k', 'k', 'SPRP'), ('qlb', 'qlb', 'NN'), ('hA', 'hA', 'SPRP'), ('btbq', 'btbq', 'NN'), ('y', 'y', 'SPRP'), ('mstnyAk', 'mstnyAk', 'RB'), ('t', 't', 'TNS'), ('Ey$', 'Ey$', 'VB'), ('jwA', 'jwA', 'NN'), ('h', 'h', 'SPRP'), ('lys', 'lys', 'VB'), ('t', 't', 'TNS'), ('jrH', 'jrH', 'VB'), ('fyh', 'fyh', 'PRP'), ('$xbTp', '$xbTp', 'NN')]).

sentence([('y', 'y', 'TNS'), ('|rb', '|rb', 'VB'), ('❤', '❤', 'emoj'), ('️', '️', 'NN')]).

sentence([('@', '@', 'REP'), ('DrKAlsuwaidi', 'DrKAlsuwaidi', 'username'), ('@', '@', 'MEN'), ('FawzAlzaidani', 'FawzAlzaidani', 'username'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('s&Al', 's&Al', 'NN'), ('Al', 'Al', 'ART'), ('>hm', '>hm', 'NN'), (':', ':', 'PUNC'), ('lmA*A', 'lmA*A', 'WRB'), ('?', '?', 'PUNC')]).

sentence([('ETn', 'ETn', 'NN'), ('y', 'y', 'SPRP'), ('vbAt', 'vbAt', 'NN'), ('Any', 'Any', 'JJ'), ('ElY', 'ElY', 'IN'), ('Al', 'Al', 'ART'), ('bAl', 'bAl', 'NN'), ('mAzl', 'mAzl', 'VB'), ('t', 't', 'PERS'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('ETy', 'ETy', 'VB'), ('k', 'k', 'SPRP'), ('mn', 'mn', 'IN'), ('rwH', 'rwH', 'NNP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('Al', 'Al', 'ART'), ('wfA', 'wfA', 'NN'), ('mA', 'mA', 'NN'), ('t', 't', 'TNS'), ('hy~A', 'hy~A', 'VB'), ('!', '!', 'PUNC')]).

sentence([('@', '@', 'REP'), ('_El_haram', '_El_haram', 'username'), ('h', 'h', 'WRB')]).

sentence([('r$p', 'r$p', 'NN'), ('mTr', 'mTr', 'NNP'), ('lm~', 'lm~', 'VB'), ('t', 't', 'PERS'), ('jnwn', 'jnwn', 'NN'), ('A$wAq', 'A$wAq', 'NN'), ('nA', 'nA', 'SPRP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('yA', 'yA', 'RP'), ('bxt', 'bxt', 'NN'), ('nA', 'nA', 'SPRP'), ('n', 'n', 'TNS'), ('Hb', 'Hb', 'VB'), ('w', 'w', 'CC'), ('Al', 'Al', 'ART'), ('dnyA', 'dnyA', 'NN'), ('mTr', 'mTr', 'NNP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('!', '!', 'PUNC')]).

sentence([('Al', 'Al', 'ART'), ('Akl', 'Akl', 'NN'), ('fy', 'fy', 'IN'), ('Al', 'Al', 'ART'), ('TAs', 'TAs', 'NN'), ('h', 'h', 'SPRP')]).

sentence([('Allhm', 'Allhm', 'NN'), ('tqbl', 'tqbl', 'NN'), ('mnA', 'mnA', 'NN'), ('Emrt', 'Emrt', 'NN'), ('nA', 'nA', 'SPRP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('Allhm', 'Allhm', 'NN'), ('A', 'A', 'TNS'), ('gfrl', 'gfrl', 'VB'), ('nA', 'nA', 'SPRP'), ('*nwb', '*nwb', 'NN'), ('nA', 'nA', 'SPRP'), ('.', '.', 'PUNC'), ('.', '.', 'PUNC'), ('Allhm', 'Allhm', 'NN'), ('tb', 'tb', 'VB'), ('ElynA', 'ElynA', 'PRP'), ('w', 'w', 'CC'), ('EAf', 'EAf', 'VB'), ('nA', 'nA', 'SPRP'), ('w', 'w', 'CC'), ('A', 'A', 'TNS'), ('Efw', 'Efw', 'VB'), ('En', 'En', 'VB'), ('A', 'A', 'PERS'), ('.', '.', 'PUNC'), ('@', '@', 'PUNC'), ('The', 'The', 'DT'), ('Holy', 'Holy', 'JJ'), ('Mosque', 'Mosque', 'NN'), ('http://t.co/MCHiXKxvmn', 'http://t.co/MCHiXKxvmn', 'link')]).

sentence([('http://t.co/ea3ZWjEa5d', 'http://t.co/ea3ZWjEa5d', 'link')]).

sentence([('A*A', 'A*A', 'IN'), ('$ftyny', '$ftyny', 'JJ'), ('Akl', 'Akl', 'NN'), ('mEmwl', 'mEmwl', 'JJ'), ('AErf', 'AErf', 'NN'), ('y', 'y', 'SPRP'), ('Any', 'Any', 'JJ'), ('w', 'w', 'CC'), ('Sl', 'Sl', 'VB'), ('t', 't', 'PERS'), ('AElY', 'AElY', 'JJ'), ('mrAHl', 'mrAHl', 'NN'), ('Al', 'Al', 'ART'), ('jwE', 'jwE', 'NN'), ('.', '.', 'PUNC')]).

sentence([('mwEd', 'mwEd', 'NN'), ('l', 'l', 'IN'), ('qAG', 'qAG', 'NN'), ('w', 'w', 'CC'), ('ETr', 'ETr', 'NN'), ('yn', 'yn', 'AGR'), ('w', 'w', 'CC'), ('bAq', 'bAq', 'VB'), ('t', 't', 'PERS'), ('w', 'w', 'CC'), ('rd', 'rd', 'VB'), ('COMMA', 'COMMA', 'COMMA'), ('w$wyp', 'w$wyp', 'JJ'), ('swAlf', 'swAlf', 'NN'), ('En', 'En', 'IN'), ('Al', 'Al', 'ART'), ('$tAG', '$tAG', 'NN'), ('-', '-', 'PUNC'), ('qhwty', 'qhwty', 'JJ'), ('wsT', 'wsT', 'NN'), ('w', 'w', 'CC'), ('qhwt', 'qhwt', 'NN'), ('k', 'k', 'SPRP'), ('srd', 'srd', 'NN'), ('COMMA', 'COMMA', 'COMMA'), ('w', 'w', 'CC'), ('ElAqt', 'ElAqt', 'NN'), ('y', 'y', 'SPRP'), ('w', 'w', 'CC'), ('y', 'y', 'TNS'), ('Ak', 'Ak', 'VB'), ('w', 'w', 'CC'), ('yA', 'yA', 'VB'), ('Al', 'Al', 'ART'), ('$tA', '$tA', 'NN'), ('wd', 'wd', 'NNP'), ('COMMA', 'COMMA', 'COMMA')]).

sentence([('@', '@', 'REP'), ('zllx9', 'zllx9', 'username'), ('w', 'w', 'CC'), ('Aw', 'Aw', 'VB')]).

sentence([('Prt', 'Prt', 'NN')]).

